// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBv2_KArLuBoGMMKzqeI4YpKpeC6SUUlw',
    appId: '1:473209005427:android:995952d55472d4e46c1106',
    messagingSenderId: '473209005427',
    projectId: 'testing-analyti',
    storageBucket: 'testing-analyti.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADY6onS5MIZn5rAANmhHgRDP2f_wCzDB0',
    appId: '1:473209005427:ios:474a1edc5ae869986c1106',
    messagingSenderId: '473209005427',
    projectId: 'testing-analyti',
    storageBucket: 'testing-analyti.appspot.com',
    iosClientId: '473209005427-cvicuobtmr1rvppi5tb43oh20ata7hc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.datingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADY6onS5MIZn5rAANmhHgRDP2f_wCzDB0',
    appId: '1:473209005427:ios:474a1edc5ae869986c1106',
    messagingSenderId: '473209005427',
    projectId: 'testing-analyti',
    storageBucket: 'testing-analyti.appspot.com',
    iosClientId: '473209005427-cvicuobtmr1rvppi5tb43oh20ata7hc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.datingApp',
  );
}
